name: Smart Contracts CI

on:
  push:
    branches:
      - main
      - "feature/**"  # Trigger workflow for feature branches
  pull_request:
    branches:
      - main

jobs:
  test-smart-contracts:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js and Yarn
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn # Automatically cache Yarn dependencies

      # Step 3: Install dependencies with frozen lockfile
      - name: Install dependencies
        run: |
          cd smart-contracts
          yarn install --frozen-lockfile

      # Step 4: Compile contracts
      - name: Compile contracts
        run: |
          cd smart-contracts
          yarn compile

      # Step 5: Generate TypeChain files
      - name: Generate TypeChain files
        run: |
          cd smart-contracts
          yarn typechain

      # Step 6: Run tests
      - name: Run tests
        run: |
          cd smart-contracts
          yarn test
